version: '2'

services:
  owncloud:
    # Image was: owncloud/appliance:10.3.2
    # Image was: owncloud/appliance:10.4.1
    image: "docker.software-univention.de/owncloud-owncloud:10.4.1"
    network_mode: bridge
    restart: always
    links:
    - "redis:redis"
    environment:
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_ADMIN_USERNAME: owncloud
      OWNCLOUD_ADMIN_PASSWORD: owncloud
      OWNCLOUD_SUB_URL: /owncloud
      OWNCLOUD_VOLUME_CONFIG: /var/lib/univention-appcenter/apps/owncloud/conf
      OWNCLOUD_VOLUME_FILES: /var/lib/univention-appcenter/apps/owncloud/data/files
      OWNCLOUD_VOLUME_CERTS: /var/lib/univention-appcenter/apps/owncloud/data/certs
      OWNCLOUD_VOLUME_APPS: /var/lib/univention-appcenter/apps/owncloud/data/custom
      OWNCLOUD_VOLUME_SESSIONS: /var/lib/univention-appcenter/apps/owncloud/data/sessions
      OWNCLOUD_MYSQL_UTF8MB4: "true"
      OWNCLOUD_REDIS_ENABLED: "true"
      OWNCLOUD_REDIS_HOST: redis
      OWNCLOUD_REDIS_PORT: 6379
      OWNCLOUD_DOMAIN: "@%@hostname@%@.@%@domainname@%@"  
  
  
  
  redis:
    # Image was: webhippie/redis:latest
    # Image was: webhippie/redis:latest
    image: "docker.software-univention.de/owncloud-redis:10.4.1"
    network_mode: bridge
    restart: always
    environment:
      REDIS_DATABASES: 1