version: '2'
# References:
# - https://docs.software-univention.de/app-center/5.0/en/get_started.html#create-a-multi-container-app
# - https://confluence.owncloud.com/display/OG/Appliance+Release

services:
  owncloud:
    # Image was: owncloud/appliance:10.3.2
    image: owncloud/appliance:10.12.2
    network_mode: bridge
    restart: always
    links:
    - "redis:redis"
    environment:
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_ADMIN_USERNAME: owncloud
      OWNCLOUD_ADMIN_PASSWORD: owncloud
      # CAUTION: Keep in sync with app-settings.ini
      OWNCLOUD_SUB_URL: /owncloud
      OWNCLOUD_VOLUME_CONFIG: /var/lib/univention-appcenter/apps/owncloud/conf
      OWNCLOUD_VOLUME_FILES: /var/lib/univention-appcenter/apps/owncloud/data/files
      OWNCLOUD_VOLUME_CERTS: /var/lib/univention-appcenter/apps/owncloud/data/certs
      OWNCLOUD_VOLUME_APPS: /var/lib/univention-appcenter/apps/owncloud/data/custom
      OWNCLOUD_VOLUME_SESSIONS: /var/lib/univention-appcenter/apps/owncloud/data/sessions
      OWNCLOUD_MYSQL_UTF8MB4: "true"
      OWNCLOUD_REDIS_ENABLED: "true"
      OWNCLOUD_REDIS_HOST: redis
      OWNCLOUD_REDIS_PORT: 6379
      # CAUTION: Keep in sync with app-settings.ini
      OWNCLOUD_DOMAIN: "@%@hostname@%@.@%@domainname@%@"
      # CAUTION: Keep in sync with app-settings.ini
      OWNCLOUD_TRUSTED_DOMAINS: "@%@hostname@%@.@%@domainname@%@,@%@interfaces/eth0/address@%@"

  redis:
    # Image was: webhippie/redis:latest
    image: webhippie/redis:latest
    network_mode: bridge
    restart: always
    environment:
      REDIS_DATABASES: 1
